security:
    role_hierarchy:
        ROLE_JOURNALIST:
        - ROLE_ADMIN
        - ROLE_FDC_TRANSLATOR_MASTER
        - ROLE_THEME
        - ROLE_BASE_ADMIN_TAG_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_TAG_ADMIN
        - ROLE_NEWS
        - ROLE_STATEMENTS
        - ROLE_INFOS
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_IMAGE_SIMPLE_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_FILM_PROJECTION_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_AUDIO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_MEDIA_VIDEO_FILM_FILM_ASSOCIATED_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_MEDIA_ADMIN
        - ROLE_BASE_ADMIN_GALLERY_DUAL_ALIGN_MEDIA_ADMIN
        - ROLE_TRANSLATE_FR
        - ROLE_TRANSLATE_EN
        - ROLE_TRANSLATE_ES
        - ROLE_TRANSLATE_ZH
