sonata_media:
    # if you don't use default namespace configuration
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
    default_context: media_image
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr
    contexts:
        # SOIF
        film_image:
            providers:
               - sonata.media.provider.image
            formats:
                mobile: { width: 584 , height: 794 , quality: 100, constraint: false }
                tiny:  { width: 76, height: 92, quality: 100, constraint: false }
                small: { width: 256 , height: 348 , quality: 100, constraint: false }
                300x400: { width: 300 , height: 400 , quality: 100, constraint: false }
                420x560: { width: 420 , height: 560 , quality: 100, constraint: false }
                searchtiny: { width: 52 , height: 66 , quality: 100, constraint: false }
                search: { width: 170 , height: 231 , quality: 100, constraint: false }
        # SOIF
        film_director:
            providers:
               - sonata.media.provider.image
            formats:
                mobile:  { width: 584 , height: 794 , quality: 100, constraint: false }
                tiny:    { width: 76, height: 92, quality: 100, constraint: false }
                small:   { width: 584 , height: 794 , quality: 100, constraint: false }
                38x46:   { width: 38 , height: 46 , quality: 100, constraint: false }
                212x134: { width: 212 , height: 134 , quality: 100, constraint: false }
                210x284: { width: 210 , height: 284 , quality: 100, constraint: false }
                976x535: { width: 976 , height: 535 , quality: 100, constraint: false }
                384x485: { width: 384 , height: 485 , quality: 100, constraint: false }
                640x603: { width: 384 , height: 485 , quality: 100, constraint: false }
                976x535: { width: 976 , height: 535 , quality: 100, constraint: false }
                searchtiny: { width: 52 , height: 66 , quality: 100, constraint: false }
                search: { width: 170 , height: 231 , quality: 100, constraint: false }

        film_image_cover:
            providers:
                - sonata.media.provider.image
            formats:
                2560x1103: { width: 2560, height: 1103, quality: 100, constraint: false }

        film_poster:
            providers:
                - sonata.media.provider.image
            formats:
                mobile: { width: 584 , height: 794 , quality: 100 }
                tiny:     { width: 46 , height: 64 , quality: 100 }
                135x185:    { width: 135 , height: 185 , quality: 100 }
                small:    { width: 187 , height: 255 , quality: 100 }
                big:      { width: 1000 , quality: 100 }
                319x434:  { width: 319 , height: 434 , quality: 100 }
                420x560: { width: 420, height: 560, quality: 100 }
                300x400: { width: 300 , height: 400 , quality: 100 }
                976x535: { width: 976 , height: 535 , quality: 100 }
                210x284: { width: 210 , height: 284 , quality: 100 }
                293x397: { width: 293, height: 397, quality: 100 }
                588x784: { width: 588, height: 784, quality: 100 }
                259x352: { width: 259, height: 352, quality: 100 }
                976x535: { width: 976 , height: 535 , quality: 100 }
                366x488: { width: 366 , height: 488 , quality: 100 }
                2560x1103: { width: 2560, height: 1103 , quality: 100 }
                516x688: { width: 516, height: 688 , quality: 100 }
                55x75: { width: 55 , height: 75 , quality: 100 }
                90x120: { width: 90 , height: 120 , quality: 100 }
                444x600: { width: 444, height: 600, quality: 100 }
                searchtiny: { width: 52 , height: 66 , quality: 100 }
                search: { width: 170 , height: 231 , quality: 100 }

        film_main:
            providers:
                - sonata.media.provider.image
            formats:
                  mobile: { width: 584 , height: 794 , quality: 100 }
                  tiny:  { width: 46 , height: 64 , quality: 100 }
                  small: { width: 187 , height: 255 , quality: 100 }
                  135x185:    { width: 135 , height: 185 , quality: 100 }
                  300x400: { width: 300, height: 400, quality 100 }
                  319x434:  { width: 319 , height: 434 , quality: 100 }
                  420x560: { width: 420, height: 560, quality: 100 }
                  big:   { width: 1000 , quality: 100 }
                  210x284: { width: 210 , height: 284 , quality: 100 }
                  293x397: { width: 293, height: 397, quality: 100 }
                  259x352: { width: 259, height: 352, quality: 100 }
                  588x784: { width: 588 , height: 784 , quality: 100 }
                  976x535: { width: 976 , height: 535 , quality: 100 }
                  366x488: { width: 366 , height: 488 , quality: 100 }
                  2560x1103: { width: 2560, height: 1103 , quality: 100 }
                  516x688: { width: 516, height: 688 , quality: 100 }
                  55x75: { width: 55 , height: 75 , quality: 100 }
                  90x120: { width: 90 , height: 120 , quality: 100 }
                  444x600: { width: 444, height: 600, quality: 100 }
                  searchtiny: { width: 52 , height: 66 , quality: 100 }
                  search: { width: 170 , height: 231 , quality: 100 }

        film_film:
            providers:
                - sonata.media.provider.image
            formats:
                mobile:  { width: 584 , height: 794 , quality: 100 }
                tiny:    { width: 146 , quality: 100 }
                square:  { width: 146, height: 146, quality: 100 }
                small:   { width: 187, height: 255, quality: 100 }
                135x185:    { width: 135 , height: 185 , quality: 100 }
                300x400: { width: 300, height: 400, quality: 100 }
                293x397: { width: 293, height: 397, quality: 100 }
                319x434: { width: 319, height: 434, quality: 100 }
                384x485: { width: 384, height: 485, quality: 100 }
                420x560: { width: 420, height: 560, quality: 100 }
                small:   { width: 500, quality: 100 }
                big:     { width: 1000, quality: 100 }
                highres: { width: 2500, quality: 100 }
                212x134: { width: 212, height: 134, quality: 100 }
                210x284: { width: 210, height: 284, quality: 100 }
                259x352: { width: 259, height: 352, quality: 100 }
                640x603: { width: 384, height: 485, quality: 100 }
                976x535: { width: 976, height: 535, quality: 100 }
                588x784: { width: 588 , height: 784 , quality: 100 }
                366x488: { width: 366 , height: 488 , quality: 100 }
                2560x1103: { width: 2560, height: 1103 , quality: 100 }
                516x688: { width: 516, height: 688 , quality: 100 }
                55x75: { width: 55 , height: 75 , quality: 100 }
                90x120: { width: 90 , height: 120 , quality: 100 }
                444x600: { width: 444, height: 600, quality: 100 }
                searchtiny: { width: 52 , height: 66 , quality: 100 }
                search: { width: 170 , height: 231 , quality: 100 }

        pdf:
            providers:
                - sonata.media.provider.pdf
            formats:
                319x434:  { width: 319 , height: 434 , quality: 100 }

        #CMS
        media_image:  # the default context is mandatory
            providers:
                - sonata.media.provider.image

            formats:
                mobile: { width: 584 , height: 794 , quality: 100, constraint: false}
                # Slider Home(TEMPORAIRE CAR NON DEFINI), audio fullscreen (TEMPORAIRE CAR NON DEFINI)
                2560x1620: { width: 2560 , height: 1620 , quality: 100, constraint: false}
                # Diaporama photo
                1760x1108: { width: 1760 , height: 1108 , quality: 100, constraint: false}
                # Miniatures diaporama photo
                194x128: { width: 194 , height: 128 , quality: 100, constraint: false}
                # Les chaînes, autre chaînes (webtv)
                586x370: { width: 586 , height: 370 , quality: 100, constraint: false}
                # Actualités à la une, Tous les articles
                1144x724: { width: 1144 , height: 724 , quality: 100, constraint: false}
                # pre-footer homepage
                1954x1200: { width: 1954 , height: 1200 , quality: 100, constraint: false}
                # Vidéo à la une, Toutes les photos, Toutes les vidéos, Chaînes festival
                640x404: { width: 640 , height: 404 , quality: 100, constraint: false}
                # Vidéo à la une, Toutes les photos, Toutes les vidéos, Chaînes festival portrait
                320x404: { width: 320 , height: 404 , quality: 100, constraint: false}
                # Pushs
                650x410: { width: 650 , height: 410 , quality: 100, constraint: false}
                # Ma Selection
                424x266: { width: 424 , height: 266 , quality: 100, constraint: false}
                # Image principale Actu
                1950x1232: { width: 1950 , height: 1232 , quality: 100, constraint: false}
                # Diaporama photo
                1266x798: { width: 1266 , height: 798 , quality: 100, constraint: false}
                # WebTv Tetiere, Channels Tetiere
                1920x450: { width: 1920 , height: 450 , quality: 100, constraint: false}
                # Dernières vidéos (webtv)
                463x292: { width: 463 , height: 292 , quality: 100, constraint: false}
                # srcset
                1280x808: { width: 1280 , height: 808 , quality: 100, constraint: false}
                # Last videos channels
                926x584: { width: 926 , height: 584 , quality: 100, constraint: false}
                # Articles focus
                918x580: { width: 918 , height: 580 , quality: 100, constraint: false}
                # Articles le même jour
                590x370: { width: 590 , height: 370 , quality: 100, constraint: false}
                # Articles Press Homepage
                265x165: { width: 265 , height: 165 , quality: 100, constraint: false}
                # Détail
                97x61: { width: 97 , height: 61 , quality: 100, constraint: false}
                # WebTv trailer navigation
                293x185: { width: 293 , height: 185 , quality: 100, constraint: false}
                # WebTv trailer film poster
                135x185: { width: 135 , height: 185 , quality: 100, constraint: false}
                # Grid Press Download #
                146x146: { width: 146 , height: 146 , quality: 100, constraint: false}
                # Event list #
                976x615: { width: 976 , height: 615 , quality: 100, constraint: false}
                ##### OLDS #####
                1980x300: { width: 1980 , height: 300 , quality: 100, constraint: false}
                #Widget Mosaic Movie Widget
                368x500: { width: 368, height: 500, quality: 100, constraint: false}

        media_image_simple:
            providers:
                - sonata.media.provider.image

            formats:
                mobile: { width: 584 , height: 794 , quality: 100, constraint: false }
                small:   { width: 187, height: 255, quality: 100, constraint: false }
                212x134: { width: 212 , height: 134 , quality: 100, constraint: false }
                293x185: { width: 293 , height: 185 , quality: 100, constraint: false }
                #event mosaic movie widget
                180x240: { width: 180 , height: 240 , quality: 100, constraint: false }
                #film
                366x488: { width: 366 , height: 488 , quality: 100, constraint: false }
                55x75: { width: 55 , height: 75 , quality: 100, constraint: false }
                90x120: { width: 90 , height: 120 , quality: 100, constraint: false }
                444x600: { width: 444, height: 600, quality: 100, constraint: false }
                #Photo Jury
                640x603: { width: 640 , height: 603 , quality: 100, constraint: false }
                # Movie VideoMain
                588x784: { width: 588 , height: 784 , quality: 100, constraint: false }
                # PressDownload
                240x326: { width: 240 , height: 326 , quality: 100, constraint: false }
                543x326: { width: 543 , height: 326 , quality: 100, constraint: false }
                # PressDownload Video image
                976x535: { width: 976 , height: 535 , quality: 100, constraint: false }
                # PressDownload Signature image
                233x233: { width: 233 , height: 233 , quality: 100, constraint: false }
                # PressCinemaMap || PressCinemaZone
                646x567: { width: 646 , height: 567 , quality: 100, constraint: false }

                586x370: { width: 586 , height: 370 , quality: 100, constraint: false }
                1280x808: { width: 1280 , height: 808 , quality: 100, constraint: false }
                2560x1103: { width: 2560, height: 1103 , quality: 100, constraint: false }
                640x404: { width: 640 , height: 404 , quality: 100, constraint: false }
                # Pushs
                650x410: { width: 650 , height: 410 , quality: 100, constraint: false }
                # PressGuide
                363x229: { width: 363 , height: 229 , quality: 100, constraint: false }
                #palmares film
                256x348: { width: 256 , height: 348 , quality: 100, constraint: false }
                384x485: { width: 384 , height: 485 , quality: 100, constraint: false }
                1954x1200: { width: 1954 , height: 1200 , quality: 100, constraint: false}
                # Participate
                363x260: { width: 363 , height: 260 , quality: 100, constraint: false }
                228x181: { width: 228 , height: 181 , quality: 100, constraint: false }
                # Partners logo
                220x85: { width: 220 , height: 85, quality: 100, constraint: false }
                # Partners portrait
                60x81: { width: 60, height: 81, quality: 100, constraint: false }
                # Search
                searchtiny: { width: 52 , height: 66 , quality: 100, constraint: false }
                search: { width: 170 , height: 231 , quality: 100, constraint: false }
                # trailer
                135x185:    { width: 135 , height: 185 , quality: 100 }

        media_audio:
            providers:
               - sonata.media.provider.audio

            formats:
                mp3: { quality: 100 }

        media_video:
            providers:
                - sonata.media.provider.video

            formats:

        seo_file:
            providers:
                - sonata.media.provider.image
            formats:
                mobile: { width: 584 , height: 794 , quality: 100, constraint: false }
                small: { width: 400 , quality: 100, constraint: false }

        media_archive:
            providers:
                - sonata.media.provider.archive
            formats:


    cdn:
        server:
            path:  http://%s3_global_bucket_name%.s3-website-%s3_global_region%.amazonaws.com

    providers:
        image:
            resizer: sonata.media.resizer.fixedDimensions
            filesystem: sonata.media.filesystem.s3
            allowed_extensions: ['jpg', 'png', 'jpeg', 'gif']
            allowed_mime_types: ['image/pjpeg','image/jpeg','image/png','image/x-png', 'image/gif']

    filesystem:
        s3:
            bucket: %s3_global_bucket_name%
            accessKey: %s3_access_key%
            secretKey: %s3_secret_key%
            region: %s3_global_region%
            storage: standard
            acl: owner_full_control
            create: false

    #providers:
    #   path: /uploads/media
    #
    #filesystem:
    #    local:
    #        directory:  %kernel.root_dir%/../web/uploads/media
    #        create:     false