twig:
    globals:
        locales: "%locales%"
        locale_fallback: "%%locale_fallback%"
        locale_default_translation: "%locale_default_translation%"
        fdc_app_android_download_url: "%fdc_app_android_download_url%"
        fdc_app_ios_download_url: "%fdc_app_ios_download_url%"
        header_account: "%header_account%"
        partner_chopard_fr: "%partner_chopard_fr%"
        partner_loreal_fr: "%partner_loreal_fr%"
        partner_hp_fr: "%partner_hp_fr%"
        partner_kering_fr: "%partner_kering_fr%"
        partner_renault_fr: "%partner_renault_fr%"
        partner_mastercard_fr: "%partner_mastercard_fr%"
        partner_chopard_en: "%partner_chopard_en%"
        partner_loreal_en: "%partner_loreal_en%"
        partner_hp_en: "%partner_hp_en%"
        partner_kering_en: "%partner_kering_en%"
        partner_renault_en: "%partner_renault_en%"
        partner_mastercard_en: "%partner_mastercard_en%"
        partner_mastercard_es: "%partner_mastercard_es%"
        partner_chopard_es: "%partner_chopard_es%"
        partner_loreal_es: "%partner_loreal_es%"
        partner_hp_es: "%partner_hp_es%"
        partner_kering_es: "%partner_kering_es%"
        partner_renault_es: "%partner_renault_es%"
        partner_mastercard_es: "%partner_mastercard_es%"
        partner_chopard_zh: "%partner_chopard_zh%"
        partner_loreal_zh: "%partner_loreal_zh%"
        partner_hp_zh: "%partner_hp_zh%"
        partner_kering_zh: "%partner_kering_zh%"
        partner_renault_zh: "%partner_renault_zh%"
        partner_mastercard_zh: "%partner_mastercard_zh%"
        footer_boutique: "%footer_boutique%"
        social_appli: "%social_appli%"
        social_facebook: "%social_facebook%"
        social_twitter: "%social_twitter%"
        social_instagram: "%social_instagram%"
        social_tumblr: "%social_tumblr%"
        social_rss_fr: "%social_rss_fr%"
        social_rss_en: "%social_rss_en%"
        social_rss_es: "%social_rss_es%"
        social_rss_zh: "%social_rss_zh%"
        social_youtube: "%social_youtube%"
        social_dailymotion: "%social_dailymotion%"
        social_podcast_fr: "%social_podcast_fr%"
        social_podcast_en: "%social_podcast_en%"
        social_podcast_es: "%social_podcast_es%"
        social_podcast_zh: "%social_podcast_zh%"
        jwplayer_key: "%jwplayer_key%"
        fdc_event_domain: "%fdc_event_domain%"
        fdc_event_scheme: "%fdc_event_scheme%"
        admin_routes_translation_legend_without_master: %admin_routes_translation_legend_without_master%
        admin_routes_translation_legend: %admin_routes_translation_legend%
        admin_routes_translation_lock: %admin_routes_translation_lock%
        #homepage
        admin_homepage_id: %admin_homepage_id%
        admin_homepage_corporate_id: %admin_homepage_corporate_id%
        # prepare / participate
        admin_fdc_page_prepare_id: %admin_fdc_page_prepare_id%
        admin_event_fdc_page_prepare_id: %admin_event_fdc_page_prepare_id%
        admin_event_fdc_page_participate_id: %admin_event_fdc_page_participate_id%
        admin_corpo_movie_inscription_id: "%admin_corpo_movie_inscription_id%"
        # corpo mediatheque
        admin_fdc_page_mediatheque_id: %admin_fdc_page_mediatheque_id%
        admin_corpo_mediatheque_id: %admin_corpo_mediatheque_id%
        # corpo search
        admin_corpo_search_id: %admin_corpo_mediatheque_id%
        #s3
        s3_server_global: http://%s3_global_bucket_name%.s3-website-%s3_global_region%.amazonaws.com/
        s3_server_video: http://%s3_video_bucket_name%.s3-website-%s3_video_region%.amazonaws.com/
        s3_server_audio: http://%s3_audio_bucket_name%.s3-website-%s3_audio_region%.amazonaws.com/
        #press
        admin_press_homepage_id: %admin_press_homepage_id%
        admin_press_guide_id: %admin_press_guide_id%
        admin_press_contact_id: %admin_press_contact_id%
        admin_press_download_id: %admin_press_download_id%
        admin_press_medialibrary_id: %admin_press_medialibrary_id%
        admin_press_accredit_id: %admin_press_accredit_id%
        admin_press_cinemamap_id: %admin_press_cinemamap_id%
        admin_press_projection_id: %admin_press_projection_id%
        admin_press_statementinfo_id: %admin_press_statementinfo_id%
        #webtv
        admin_fdc_page_web_tv_live_id: %admin_fdc_page_web_tv_live_id%
        admin_fdc_page_web_tv_channels_id: %admin_fdc_page_web_tv_channels_id%
        admin_fdc_page_web_tv_trailers_competition_id: %admin_fdc_page_web_tv_trailers_competition_id%
        admin_fdc_page_web_tv_trailers_certain_regard_id: %admin_fdc_page_web_tv_trailers_certain_regard_id%
        admin_fdc_page_web_tv_trailers_hors_competition_id: %admin_fdc_page_web_tv_trailers_hors_competition_id%
        admin_fdc_page_web_tv_trailers_seances_speciales_id: %admin_fdc_page_web_tv_trailers_seances_speciales_id%
        admin_fdc_page_web_tv_trailers_cinefondation_id: %admin_fdc_page_web_tv_trailers_cinefondation_id%
        admin_fdc_page_web_tv_trailers_courts_metrages_id: %admin_fdc_page_web_tv_trailers_courts_metrages_id%
        admin_fdc_page_web_tv_trailers_cannes_classics_id: %admin_fdc_page_web_tv_trailers_cannes_classics_id%
        admin_fdc_page_web_tv_trailers_cinema_plage_id: %admin_fdc_page_web_tv_trailers_cinema_plage_id%
        #news
        admin_fdc_page_news_articles_id: %admin_fdc_page_news_articles_id%
        admin_fdc_page_news_audios_id: %admin_fdc_page_news_audios_id%
        admin_fdc_page_news_videos_id: %admin_fdc_page_news_videos_id%
        admin_fdc_page_news_images_id: %admin_fdc_page_news_images_id%
        #la selection
        admin_fdc_page_la_selection_competition_id: %admin_fdc_page_la_selection_competition_id%
        admin_fdc_page_la_selection_certain_regard_id: %admin_fdc_page_la_selection_certain_regard_id%
        admin_fdc_page_la_selection_hors_competition_id: %admin_fdc_page_la_selection_hors_competition_id%
        admin_fdc_page_la_selection_seances_speciales_id: %admin_fdc_page_la_selection_seances_speciales_id%
        admin_fdc_page_la_selection_cinefondation_id: %admin_fdc_page_la_selection_cinefondation_id%
        admin_fdc_page_la_selection_courts_metrages_id: %admin_fdc_page_la_selection_courts_metrages_id%
        admin_fdc_page_la_selection_cinema_plage_id: %admin_fdc_page_la_selection_cinema_plage_id%
        #jury
        admin_fdc_page_jury_certain_regard_id: %admin_fdc_page_jury_certain_regard_id%
        admin_fdc_page_jury_camera_dor_id: %admin_fdc_page_jury_camera_dor_id%
        admin_fdc_page_jury_long_metrages_id: %admin_fdc_page_jury_long_metrages_id%
        admin_fdc_page_jury_cinefondation_courts_metrages_id: %admin_fdc_page_jury_cinefondation_courts_metrages_id%
        #award
        admin_fdc_page_award_competition_id: %admin_fdc_page_award_competition_id%
        admin_fdc_page_award_certain_regard_id: %admin_fdc_page_award_certain_regard_id%
        admin_fdc_page_award_cinefondation_id: %admin_fdc_page_award_cinefondation_id%
        admin_fdc_page_award_camera_dor_id: %admin_fdc_page_award_camera_dor_id%
        admin_fdc_page_award_all_awards_id: %admin_fdc_page_award_all_awards_id%
        admin_fdc_page_event_id: %admin_fdc_page_event_id%
        #orange
        admin_fdc_orange_series_id: %admin_fdc_orange_series_id%
        admin_fdc_orange_vod_id: %admin_fdc_orange_vod_id%
        admin_fdc_orange_studio_id: %admin_fdc_orange_studio_id%
        #footer
        admin_fdc_footer_confidentialite_id: %admin_fdc_footer_confidentialite_id%
        admin_fdc_footer_mentions_legales_id: %admin_fdc_footer_mentions_legales_id%
        admin_fdc_footer_credits_id: %admin_fdc_footer_credits_id%
        #satellite
        header_fdc_com: '%header_fdc_com%'
        header_fdc_fr: '%header_fdc_fr%'
        header_cine_fr: '%header_cine_fr%'
        header_ccm_fr: '%header_ccm_fr%'
        header_mdf_fr: '%header_mdf_fr%'
        header_fdc_en: '%header_fdc_en%'
        header_cine_en: '%header_cine_en%'
        header_ccm_en: '%header_ccm_en%'
        header_mdf_en: '%header_mdf_en%'
        header_fdc_es: '%header_fdc_es%'
        header_cine_es: '%header_cine_es%'
        header_ccm_es: '%header_ccm_es%'
        header_mdf_es: '%header_mdf_es%'
        header_fdc_zh: '%header_fdc_zh%'
        header_cine_zh: '%header_cine_zh%'
        header_ccm_zh: '%header_ccm_zh%'
        header_mdf_zh: '%header_mdf_zh%'
        selfkit_amazon_url: "%selfkit_amazon_url%"
        mdf_google_analytics_first_id: '%mdf_google_analytics_first_id%'
        mdf_google_analytics_second_id: '%mdf_google_analytics_second_id%'
        mdf_hide_ch_language: '%mdf_hide_ch_language%'
